(function(){
  "use strict";
  const engine=window.TrumpTvEngine,catalog=window.TRUMP_TV_CATALOG,blocks=window.TRUMP_TV_BLOCKS,$=id=>document.getElementById(id);
  const els={clock:$("stationClock"),mode:$("modeLabel"),title:$("nowTitle"),source:$("sourceLine"),time:$("programTime"),enter:$("enterButton"),station:$("stationCard"),stationLabel:$("stationCardLabel"),stationTitle:$("stationCardTitle"),stationCountdown:$("stationCardCountdown"),stationLink:$("stationCardLink"),start:$("startOverButton"),rewind:$("rewindButton"),live:$("liveButton"),share:$("shareButton"),shareStatus:$("shareStatus"),position:$("positionLabel"),remaining:$("remainingLabel"),progress:$("progressBar"),next:$("nextCards"),guide:$("guideRows"),guideDate:$("guideDate")};
  let schedule=[],scheduleKey="",player=null,playerReady=false,apiRequested=false,entered=false,loadedKey="",mode="live",timeShiftBaseMs=0,timeShiftStartedMs=0;const failed=new Set();
  const activeMs=()=>mode==="live"?Date.now():timeShiftBaseMs+(Date.now()-timeShiftStartedMs);
  const formatTime=ms=>new Intl.DateTimeFormat("en-US",{timeZone:engine.TIME_ZONE,hour:"numeric",minute:"2-digit"}).format(new Date(ms));
  const formatDuration=seconds=>{const m=Math.max(0,Math.ceil(seconds/60));return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m} min`;};
  function ensureSchedule(ms){const key=engine.dateKey(ms);if(key!==scheduleKey){scheduleKey=key;schedule=engine.createDaySchedule(ms,catalog,blocks).filter(x=>!failed.has(x.program.videoId));renderGuide();}}
  function renderGuide(){if(!schedule.length)return;els.guideDate.textContent=new Intl.DateTimeFormat("en-US",{timeZone:engine.TIME_ZONE,weekday:"long",month:"long",day:"numeric"}).format(new Date(schedule[0].startsAtMs));const rows=[];let previousBlock="";for(const item of schedule){if(item.block.id===previousBlock)continue;previousBlock=item.block.id;const first=schedule.find(x=>x.block.id===item.block.id);const last=[...schedule].reverse().find(x=>x.block.id===item.block.id);rows.push(`<article class="guide-row" data-block="${item.block.id}"><time>${formatTime(first.startsAtMs)}–${formatTime(last.endsAtMs)}</time><strong>${item.block.label}</strong><span>${item.block.description}</span></article>`);}els.guide.innerHTML=rows.join("");}
  let renderedNextBlockKey = "";
  function renderNext(current){
    const nextBlockKey = current ? String(current.id || current.startsAtMs || "") + ":" + String((current.movie && current.movie.videoId) || (current.program && current.program.videoId) || "") : "";
    if (nextBlockKey && nextBlockKey === renderedNextBlockKey) return;
    renderedNextBlockKey = nextBlockKey;const idx=schedule.findIndex(x=>x.id===current.id);els.next.innerHTML=[1,2,3].map(step=>{const item=schedule[(idx+step)%schedule.length];return `<article class="next-card"><time>${formatTime(item.startsAtMs)}</time><div><h3>${item.program.title}</h3><p>${item.program.source} · ${item.block.label}</p></div></article>`;}).join("");}
  function showStation(program,message){els.station.hidden=false;els.stationLabel.textContent=program.sourceType||"SOURCE";els.stationTitle.textContent=program.title;els.stationCountdown.textContent=message||program.context||"Source available outside the embedded player.";if(program.sourceUrl){els.stationLink.hidden=false;els.stationLink.href=program.sourceUrl;}else{els.stationLink.hidden=true;}}
  function loadMedia(state){if(!entered)return;const p=state.item.program,key=`${state.item.id}:${p.videoId||"external"}`;if(!p.videoId){if(playerReady&&loadedKey!==key)player.stopVideo();loadedKey=key;showStation(p);return;}els.station.hidden=true;if(!playerReady)return;if(key!==loadedKey){loadedKey=key;player.loadVideoById({videoId:p.videoId,startSeconds:state.mediaSeconds});return;}if(mode==="live"&&player.getPlayerState()===YT.PlayerState.PLAYING){const drift=state.mediaSeconds-player.getCurrentTime();if(Math.abs(drift)>3)player.seekTo(state.mediaSeconds,true);}}
  function tick(){const ms=activeMs();ensureSchedule(ms);if(!schedule.length)return;const state=engine.resolve(ms,schedule);const p=state.item.program;els.clock.textContent=`${formatTime(Date.now())} local`;els.mode.textContent=mode==="live"?`LIVE · ${state.item.block.label.toUpperCase()}`:"TIME SHIFTED";els.title.textContent=p.title;els.source.textContent=`${p.source} · ${p.sourceType} — ${p.context}`;els.time.textContent=`${formatTime(state.item.startsAtMs)}–${formatTime(state.item.endsAtMs)}`;els.position.textContent=mode==="live"?"Synchronized to the viewer’s local station clock":`${formatDuration(state.elapsed)} into this block`;els.remaining.textContent=`${formatDuration(state.remaining)} remaining`;els.progress.style.width=`${Math.min(100,(state.elapsed/state.item.slotSeconds)*100)}%`;document.querySelectorAll(".guide-row").forEach(row=>row.classList.toggle("current",row.dataset.block===state.item.block.id));renderNext(state.item);loadMedia(state);}
  function loadApi(){if(apiRequested||playerReady)return;apiRequested=true;if(window.YT&&window.YT.Player){window.onYouTubeIframeAPIReady();return;}const s=document.createElement("script");s.src="https://www.youtube.com/iframe_api";s.referrerPolicy="strict-origin-when-cross-origin";document.head.appendChild(s);}
  function enter(){entered=true;els.enter.hidden=true;loadApi();tick();}
  function startOver(){ensureSchedule(Date.now());const current=engine.resolve(Date.now(),schedule).item;mode="timeshift";timeShiftBaseMs=current.startsAtMs;timeShiftStartedMs=Date.now();loadedKey="";tick();}
  function rewind(){mode="timeshift";timeShiftBaseMs=activeMs()-30000;timeShiftStartedMs=Date.now();loadedKey="";tick();}
  function joinLive(){mode="live";loadedKey="";tick();}
  async function share(){const data={title:document.title,text:`Watch ${els.title.textContent} on Trump TV Network.`,url:location.href};try{if(navigator.share){await navigator.share(data);els.shareStatus.textContent="Shared.";}else{await navigator.clipboard.writeText(location.href);els.shareStatus.textContent="Link copied.";}}catch(e){if(!e||e.name!=="AbortError")els.shareStatus.textContent="Share did not complete.";}}
  window.onYouTubeIframeAPIReady=function(){player=new YT.Player("player",{width:"100%",height:"100%",playerVars:{playsinline:1,controls:1,enablejsapi:1,rel:0,origin:location.origin,widget_referrer:location.href},events:{onReady:()=>{playerReady=true;player.unMute();player.setVolume(100);tick();},onError:()=>{const current=schedule.length?engine.resolve(activeMs(),schedule).item.program:null;if(current&&current.videoId)failed.add(current.videoId);scheduleKey="";loadedKey="";setTimeout(tick,250);}}});};
  els.enter.addEventListener("click",enter);els.start.addEventListener("click",startOver);els.rewind.addEventListener("click",rewind);els.live.addEventListener("click",joinLive);els.share.addEventListener("click",share);
  ensureSchedule(Date.now());tick();setInterval(tick,1000);
})();